# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestSFGaugeView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestSFGaugeView
  pod 'SFGaugeView', path: '../'

  target 'TestSFGaugeViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
